POST http://localhost:3000/api/invoice

{
    "invoiceNumber": "fdfddfdf",
    "totalAmount": 3433443,
    "currencyCode": "fdfddffd",
    "timestamp": "sdfdfsd.fsdsfdfs"
}

###
POST https://buggyapi.onrender.com/balance
Content-Type: application/json

{
    "amount": 100
}

###
POST http://localhost:3000/balance
Content-Type: application/json

{
    "amount": -50
}

